# Generated by Django 4.0 on 2022-08-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_knowledge_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='icon_type',
            field=models.CharField(default='fontawesome', max_length=100),
        ),
    ]
