# Generated by Django 3.2.15 on 2023-08-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_knowledge_icon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
